export default {
  desktopBackgroundLight: '#f6f7f8',
  desktopBackgroundGray: '#e9ebee',
  desktopTextPlaceholder: '#9197a3',
  desktopTextPlaceholderFocused: '#bdc1c9',
  postBackgroundWhite: '#fff',
  postSectionBorder: '1px solid #dadde1',
  tooltipColorWhite: '#fff',
  tooltipBackgroundGray: '#616770',
  tooltipBackgroundBlack: '#1c1e21',
  tooltipTopPostion: '1.5em',
  infoColorGray: '#616770',
  commentInputBackground: 'transparent',
  scrollbarFaceActiveColor: '#7d7d7d',
  scrollbarFaceColor: '#c2c2c2',
  scrollbarFaceMargin: '4px',
  scrollbarFaceRadius: '6px',
  scrollbarSize: '15px',
  scrollbarSizeLarge: '17px',
  scrollbarTrackColor: 'rgba(255, 255, 255, 0.8)',
  alignItems: 'center',
  fontFamily: 'Microsoft JhengHei',
  baseFontSize: '0.9rem',
  mobileFontSize: '0.9rem',
  reactionIconSize: '18px',
  feedbackActionButtonIconSize: '18px',
  reactedButtonColor: 'rgb(32, 120, 244)',
  reactedButtonTextColor: 'rgb(32, 120, 244)',
  commentTextBackground: '#f2f3f5',
  commentPlaceholderColor: '#8d949e',
  commentPlaceholderColorBlack: '#1c1e21',
  commentFeedbackTextColor: '#90949c',
  commentFeedbackButtonTextColor: '#385898',
  commentYoursBorderColor: '#3578e5',
  commentReactionIconSize: '16px',
  commentAttachIconSize: '16px',
  toggleMenuItemHoverBackground: '#4267b2',
  toggleMenuItemTextColor: '#1d2129',
  toggleMenuItemTextHoverColor: '#fff',
  toggleMenuItemBorderColor: '#fff',
  toggleMenuItemBorderHoverColor: '#29487d'
}
